  
all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:dbname=qdpm;host=localhost'
      profiler: false
      username: qdpm
      password: "<?php echo urlencode('StrongPasswordHere') ; ?>"
      attributes:
        quote_identifier: true  
  